apiVersion: v1
kind: Service
metadata:
  name: {{ include "airpulse-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app.kubernetes.io/name: {{ include "airpulse-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
